const express = require("express");
const multer = require("multer");
const fs = require("fs");
const path = require("path");
const {
  huffmanCompress,
  huffmanDecompress,
  rleCompress,
  rleDecompress,
  lz77Compress,
  lz77Decompress,
} = require("../compressor");

const router = express.Router();
const upload = multer({ dest: "uploads/" });

router.post("/process", upload.single("file"), async (req, res) => {
  const { operation, algorithm } = req.body;
  const uploadedFile = req.file;

  if (!uploadedFile) {
    return res.status(400).send("No file uploaded");
  }

  const inputFilePath = uploadedFile.path;
  const outputFilePath = `${uploadedFile.path}_output`;

  const startTime = Date.now();

  try {
    if (algorithm === "huffman") {
      if (operation === "compress") {
        huffmanCompress(inputFilePath, outputFilePath);
      } else {
        try {
          JSON.parse(fs.readFileSync(inputFilePath, "utf-8"));
        } catch (e) {
          throw new Error(
            "Invalid file format: Huffman decompression requires a JSON file generated by Huffman compression."
          );
        }
        huffmanDecompress(inputFilePath, outputFilePath);
      }
    } else if (algorithm === "rle") {
      if (operation === "compress") {
        rleCompress(inputFilePath, outputFilePath);
      } else {
        try {
          const content = fs.readFileSync(inputFilePath, "utf-8");
          if (!/^[\s\S]*\d+$/.test(content)) {
            throw new Error();
          }
        } catch {
          throw new Error(
            "Invalid file format: RLE decompression requires a .txt file compressed using RLE."
          );
        }
        rleDecompress(inputFilePath, outputFilePath);
      }
    } else if (algorithm === "lz77") {
      if (operation === "compress") {
        lz77Compress(inputFilePath, outputFilePath);
      } else {
        try {
          JSON.parse(fs.readFileSync(inputFilePath, "utf-8"));
        } catch (e) {
          throw new Error(
            "Invalid file format: LZ77 decompression requires a JSON file generated by LZ77 compression."
          );
        }
        lz77Decompress(inputFilePath, outputFilePath);
      }
    } else {
      throw new Error("Invalid algorithm");
    }

    const endTime = Date.now();
    const processingTimeMs = endTime - startTime;

    const originalSize = fs.statSync(inputFilePath).size;
    const outputSize = fs.statSync(outputFilePath).size;
    const ratio = originalSize === 0 ? 0 : outputSize / originalSize;

    res.set({
      "X-Original-Size": originalSize,
      "X-Output-Size": outputSize,
      "X-Processing-Time": processingTimeMs,
    });

    res.download(outputFilePath, (err) => {
      fs.unlinkSync(inputFilePath);
      fs.unlinkSync(outputFilePath);
    });
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: err.message || "Error processing file" });
  }
});
module.exports = router;
